### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by floqqi** [pyreadline/pyreadline#38]
`pyreadline` is not working on Python 3.5rc1 (on Windows 7, SP1). After installing I get the following error running `python` in command line:

``` python
Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "C:\Python35\lib\site.py", line 388, in register_readline
    import readline
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\pyreadline\__init__.py", line 11, in <module>
    from . import unicode_helper, logger, clipboard, lineeditor, modes, console
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\pyreadline\console\__init__.py", line 15, in <module>
    from .console import *
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\pyreadline\console\console.py", line 21, in <module>
    import pyreadline.unicode_helper as unicode_helper
AttributeError: module 'pyreadline' has no attribute 'unicode_helper'
```

Using `ipython` (4.0.0):

``` python
Traceback (most recent call last):
  File "C:\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\floqqi\Envs\<project>\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\IPython\__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\traitlets\config\application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\IPython\terminal\ipapp.py", line 314, in initialize
    self.init_shell()
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\IPython\terminal\ipapp.py", line 330, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\traitlets\config\configurable.py", line 380, in instance

    inst = cls(*args, **kwargs)
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\IPython\core\interactiveshell.py", line 531, in __init__

    self.init_readline()
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\IPython\core\interactiveshell.py", line 1941, in init_readline
    import IPython.utils.rlineimpl as readline
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\IPython\utils\rlineimpl.py", line 21, in <module>
    _rl = __import__(_rlmod_name)
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\pyreadline\__init__.py", line 11, in <module>
    from . import unicode_helper, logger, clipboard, lineeditor, modes, console
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\pyreadline\console\__init__.py", line 15, in <module>
    from .console import *
  File "C:\Users\floqqi\Envs\<project>\lib\site-packages\pyreadline\console\console.py", line 610, in <module>
    msvcrt = cdll.LoadLibrary(ctypes.util.find_msvcrt())
  File "C:\Python35\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python35\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: bad argument type for built-in operation
```

**Comment by uetoyo** [comment]
This will fix the issue: `import pyreadline.unicode_helper #> as unicode_helper`
in `console.py` file.

**Comment by nalvid** [comment]
The similar issue as #33?
... I thing this issue is relevant only for PyPi version of Library.

**Comment by evfro** [comment]
I can confirm it's not only PyPi version's problem. And it's failing even with released python 3.5.
I've upgraded my python with `conda install python=3.5` and seeing the same problem when trying to launch python from command prompt on Windows 10 x64

**Comment by sorz** [comment]
Same problem on Python 3.5.0 on Windows 10.

```
C:\Users\Chen>python
Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "C:\Users\Chen\AppData\Local\Programs\Python\Python35\lib\site.py", line 388, in register_readline
    import readline
  File "C:\Users\Chen\AppData\Local\Programs\Python\Python35\lib\site-packages\readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "C:\Users\Chen\AppData\Local\Programs\Python\Python35\lib\site-packages\pyreadline\__init__.py", line 11, in <module>
    from . import unicode_helper, logger, clipboard, lineeditor, modes, console
  File "C:\Users\Chen\AppData\Local\Programs\Python\Python35\lib\site-packages\pyreadline\console\__init__.py", line 15, in <module>
    from .console import *
  File "C:\Users\Chen\AppData\Local\Programs\Python\Python35\lib\site-packages\pyreadline\console\console.py", line 21, in <module>
    import pyreadline.unicode_helper as unicode_helper
AttributeError: module 'pyreadline' has no attribute 'unicode_helper'
>>>
```

**Comment by Callidior** [comment]
I had the some problem and solved it by building pyreadline from the source code of the latest commit. I think the problem has been solved in commit 2b9292ef3cd8b39203e4f2258a69160e0adfc483.

**Comment by sorz** [comment]
@Callidior It works, thanks.

```
pip install git+https://github.com/pyreadline/pyreadline.git
```

**Comment by floqqi** [comment]
Works for me, too!
@jstenar: Isn't that a good reason to release a new version? :)

**Comment by floqqi** [comment]
[Version 2.1](https://pypi.python.org/pypi/pyreadline/2.1) was released. You may close this issue. Many thanks!

**Comment by mega7star** [comment]
I have this problem in Windows 8 in pyreadline-2.1:

```
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "C:\Python351\lib\site.py", line 419, in register_readline
    readline.read_history_file(history)
  File "C:\Python351\lib\site-packages\pyreadline\rlmain.py", line 165, in read_history_file
    self.mode._history.read_history_file(filename)
  File "C:\Python351\lib\site-packages\pyreadline\lineeditor\history.py", line 82, in read_history_file
    for line in open(filename, 'r'):
  File "C:\Python351\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 2837: character maps to <undefined>
>>>
```

And I solved the problem so:
Open file `C:\Python351\lib\site-packages\pyreadline\lineeditor\history.py`.
Go to 82 line and edit: this - `for line in open(filename, 'r'):` on this - `for line in open(filename, 'r', encoding='utf-8'):`
Everything works perfectly

**Comment by HoisW** [comment]
thank you @mega7star
you solved my problem！

**Comment by Nyquis** [comment]
Appears as an issue even in python 3.6.1. 
It is sufficient to just use a utf8 encoded character such as ß.

**Comment by danger89** [comment]
yea very strange..

**Comment by nirvana-msu** [comment]
Get the same error, Window 7, pyreadline==2.1. It works fine if I just run python from console, but it fails if I try to run the console in PyCharm through a conda environment with IPython installed:

```
C:\Users\<username>\AppData\Local\Continuum\Anaconda2\envs\<envname>\python.exe "C:\Program Files (x86)\JetBrains\PyCharm 2016.2\helpers\pydev\pydevconsole.py" 63686 63687
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.2\helpers\pydev\pydevconsole.py", line 512, in <module>
    pydevconsole.start_server(pydev_localhost.get_localhost(), int(port), int(client_port))
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.2\helpers\pydev\pydevconsole.py", line 349, in start_server
    interpreter = InterpreterInterface(host, client_port, threading.currentThread())
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.2\helpers\pydev\_pydev_bundle\pydev_ipython_console.py", line 26, in __init__
    self.interpreter = get_pydev_frontend(host, client_port, show_banner=show_banner)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.2\helpers\pydev\_pydev_bundle\pydev_ipython_console_011.py", line 485, in get_pydev_frontend
    _PyDevFrontEndContainer._instance = _PyDevFrontEnd(show_banner=show_banner)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.2\helpers\pydev\_pydev_bundle\pydev_ipython_console_011.py", line 315, in __init__
    self.ipython = PyDevTerminalInteractiveShell.instance()
  File "C:\Users\<username>\AppData\Local\Continuum\Anaconda2\envs\<envname>\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\<username>\AppData\Local\Continuum\Anaconda2\envs\<envname>\lib\site-packages\IPython\terminal\interactiveshell.py", line 425, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "C:\Users\<username>\AppData\Local\Continuum\Anaconda2\envs\<envname>\lib\site-packages\IPython\core\interactiveshell.py", line 479, in __init__
    self.init_io()
  File "C:\Users\<username>\AppData\Local\Continuum\Anaconda2\envs\<envname>\lib\site-packages\IPython\terminal\interactiveshell.py", line 392, in init_io
    self.enable_win_unicode_console()
  File "C:\Users\<username>\AppData\Local\Continuum\Anaconda2\envs\<envname>\lib\site-packages\IPython\terminal\interactiveshell.py", line 385, in enable_win_unicode_console
    import win_unicode_console
  File "C:\Users\<username>\AppData\Local\Continuum\Anaconda2\envs\<envname>\lib\site-packages\win_unicode_console\__init__.py", line 2, in <module>
    from . import streams, console, readline_hook
  File "C:\Users\<username>\AppData\Local\Continuum\Anaconda2\envs\<envname>\lib\site-packages\win_unicode_console\readline_hook.py", line 129, in <module>
    pyreadline_manager = PyReadlineManager()
  File "C:\Users\<username>\AppData\Local\Continuum\Anaconda2\envs\<envname>\lib\site-packages\win_unicode_console\readline_hook.py", line 107, in __init__
    self.original_codepage = pyreadline.unicode_helper.pyreadline_codepage
AttributeError: module 'pyreadline' has no attribute 'unicode_helper'

Process finished with exit code 1
```

Relevant output from `pip freeze`:
```
> pip freeze
<...>
ipython==6.1.0
ipython-genutils==0.2.0
pyreadline==2.1
traitlets==4.3.2
win-unicode-console==0.5
```

**Comment by somenzz** [comment]
delete file [.python_history].

**Comment by dengxiongshi** [comment]
It's very good @mega7star

**Comment by chestnutjay** [comment]
> 
> 
> I have this problem in Windows 8 in pyreadline-2.1:
> 
> ```
> Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> Failed calling sys.__interactivehook__
> Traceback (most recent call last):
>   File "C:\Python351\lib\site.py", line 419, in register_readline
>     readline.read_history_file(history)
>   File "C:\Python351\lib\site-packages\pyreadline\rlmain.py", line 165, in read_history_file
>     self.mode._history.read_history_file(filename)
>   File "C:\Python351\lib\site-packages\pyreadline\lineeditor\history.py", line 82, in read_history_file
>     for line in open(filename, 'r'):
>   File "C:\Python351\lib\encodings\cp1251.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 2837: character maps to <undefined>
> >>>
> ```
> 
> And I solved the problem so:
> Open file `C:\Python351\lib\site-packages\pyreadline\lineeditor\history.py`.
> Go to 82 line and edit: this - `for line in open(filename, 'r'):` on this - `for line in open(filename, 'r', encoding='utf-8'):`
> Everything works perfectly

Thank you. This solved my problem
